# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loss_ridge_cpp <- function(y, A, x, lambda) {
    .Call(`_code815_loss_ridge_cpp`, y, A, x, lambda)
}

gradient_descent_lsq_cpp <- function(y, A, x0, lambda, gamma, tol = 0.0001, max_iter = 10000L, printing = FALSE) {
    .Call(`_code815_gradient_descent_lsq_cpp`, y, A, x0, lambda, gamma, tol, max_iter, printing)
}

loss_ridge <- function(y, A, x, lambda) {
    .Call(`_code815_loss_ridge`, y, A, x, lambda)
}

