# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loss_ridge <- function(y, A, x, lambda) {
    .Call(`_code815_loss_ridge`, y, A, x, lambda)
}

